config/routes.rb
Rails.application.routes.draw do
  # get 'pets/index'
  # get 'pets/new'
  # get 'pets/show'
  # get 'pets/edit'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'pets#index'
  resources :pets
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pet.rb
class Pet < ApplicationRecord
  validates :name, presence: true
  validates :description, length: {minimum: 10}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  def index
    @pets = Pet.all
  end

  def new
    @pet = Pet.new
  end

  def show
    @pet = Pet.find(params[:id])
  end

  def edit
    @pet = Pet.find(params[:id])
  end

  def create
    @pet = Pet.new(pet_params)
    if @pet.save
      redirect_to pet_path(@pet)
    else
      render 'new'
    end
  end

  def update
    @pet = Pet.find(params[:id])
    if @pet.update(pet_params)
      redirect_to pet_path(@pet)
    else
      render 'edit'
    end
  end

  def destroy
    @pet = Pet.find(params[:id])
    @pet.destroy
    redirect_to pets_path
  end

  private

  def pet_params
    params.require(:pet).permit(:name, :age, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LearnRor</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.css" integrity="sha512-8bHTC73gkZ7rZ7vpqUQThUDhqcNFyYi2xgDgPDHc+GXVGHXq+xPjynxIopALmOPqzo9JZj0k6OqqewdGO3EsrQ==" crossorigin="anonymous" />
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.js" integrity="sha512-dqw6X88iGgZlTsONxZK9ePmJEFrmHwpuMrsUChjAw1mRUhUITE5QU9pkcSox+ynfLhL15Sv2al5A0LVyDCmtUw==" crossorigin="anonymous"></script>
  </body>
</html>

app/views/pets/_form.html.erb
<div class="ui raised very padded text container segment">
  <%= form_with model: @pet, class: 'ui form', local: true do |form| %>
    <% if @pet.errors.any? %>
      <div class="ui red message">
        <div class="header">
          <%= pluralize(@pet.errors.count, "error") %> prohibited
          this article from being saved:
        </div>
        <ul>
          <% @pet.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div class="field">
      <%= form.label :name %><br>
      <%= form.text_field :name, placeholder: 'Name' %>
    </div>

    <div class="field">
      <%= form.label :age %><br>
      <%= form.text_field :age, placeholder: 'Age' %>
    </div>

    <div class="field">
      <%= form.label :description %><br>
      <%= form.text_area :description, placeholder: 'Description' %>
    </div>

    <%= form.submit class: 'ui button' %>
    <%= link_to('Home', pets_path, class: 'ui button') %>
  <% end %>
</div>

app/views/pets/edit.html.erb
<header>
  <h1>Pets#edit</h1>
  <p>Find me in app/views/pets/edit.html.erb</p>
  <br/>
</header>
<main>
  <%= render 'form' %>
</main>

app/views/pets/index.html.erb
<header>
  <h1>Pets#index</h1>
  <p>Find me in app/views/pets/index.html.erb</p>
  <br/>
</header>
<main>
  <div class="ui raised very padded text container segment">
    <table class="ui celled table">
      <thead>
      <tr>
        <th>Name</th>
        <th>Age</th>
        <th>Description</th>
        <th>Action</th>
      </tr>
      </thead>
      <tbody>
      <% @pets.each do |pet| %>
        <tr>
          <td data-label="Name"><%= pet.name %></td>
          <td data-label="Age"><%= pet.age %></td>
          <td data-label="Description"><%= pet.description %></td>
          <td data-label="Action">
            <%= link_to('View', pet_path(pet)) %>
            <%= link_to('New', new_pet_path) %>
            <%= link_to('Edit', edit_pet_path(pet)) %>
            <%= link_to('Remove', pet_path(pet), method: :delete) %>
            <%#= link_to('Remove', pet_path(pet), method: :delete, data: { confirm: 'Are you sure?' }) %>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</main>

app/views/pets/new.html.erb
<header>
  <h1>Pets#new</h1>
  <p>Find me in app/views/pets/new.html.erb</p>
  <br/>
</header>
<main>
  <%= render 'form' %>
</main>

app/views/pets/show.html.erb
<header>
  <h1>Pets#show</h1>
  <p>Find me in app/views/pets/show.html.erb</p>
  <br/>
</header>
<main>
  <div class="ui raised very padded text container segment">
    <div class="ui label">
      Name
      <div class="detail"><%= @pet.name %></div>
    </div>
    <div class="ui label">
      Age
      <div class="detail"><%= @pet.age %></div>
    </div>
    <div class="ui label">
      Description
      <div class="detail"><%= @pet.description %></div>
    </div>
    <br/>
    <br/>
    <%= link_to('Home', pets_path, class: 'ui button') %>
  </div>
</main>